Running on MIC and CPU
Traceback (most recent call last):
  File "/opt/apps/xalt/0.4.0/libexec/xalt_run_submission.py", line 38, in <module>
    logger = config_logger()
  File "/opt/apps/xalt/0.4.0/libexec/xalt_util.py", line 30, in config_logger
    syslog = SysLogHandler(address='/dev/log', facility='local3')
  File "/usr/lib64/python2.6/logging/handlers.py", line 721, in __init__
    self._connect_unixsocket(address)
  File "/usr/lib64/python2.6/logging/handlers.py", line 737, in _connect_unixsocket
    self.socket.connect(address)
  File "<string>", line 1, in connect
socket.error: [Errno 111] Connection refused
TACC: Starting up job 4160243
TACC: Starting parallel tasks...
  mpiexec.hydra -iface br0 -configfile /home1/02687/binren/.slurm/config_file.4160243.5VZ08ALZ -machinefile /home1/02687/binren/.slurm/job.4160243.hostlist.f8qpDH4q  
[proxy:0:1@c557-204-mic0.stampede.tacc.utexas.edu] HYDU_create_process (./utils/launch/launch.c:111): execvp error on file main.mic (Permission denied)
slurmd[c557-204]: *** JOB 4160243 CANCELLED AT 2014-09-25T19:47:33 DUE TO TIME LIMIT ***
[mpiexec@c557-204.stampede.tacc.utexas.edu] HYD_pmcd_pmiserv_send_signal (./pm/pmiserv/pmiserv_cb.c:221): assert (!closed) failed
[mpiexec@c557-204.stampede.tacc.utexas.edu] ui_cmd_cb (./pm/pmiserv/pmiserv_pmci.c:128): unable to send SIGUSR1 downstream
[mpiexec@c557-204.stampede.tacc.utexas.edu] HYDT_dmxu_poll_wait_for_event (./tools/demux/demux_poll.c:77): callback returned error status
[mpiexec@c557-204.stampede.tacc.utexas.edu] HYD_pmci_wait_for_completion (./pm/pmiserv/pmiserv_pmci.c:388): error waiting for event
[mpiexec@c557-204.stampede.tacc.utexas.edu] main (./ui/mpich/mpiexec.c:745): process manager error waiting for completion
